version: '3.3'
services:
  api:
    volumes:
    - .:/app
    build:
      context: .
      cache_from:
      - &img_tag time-tracking-app
    image: *img_tag
    depends_on:
    - redis
    - postgres

  redis:
    image: redis
    ports:
    - 6379:6379

  postgres:
    image: "postgres:11.2"
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: tta
      POSTGRES_PASSWORD: tta
      POSTGRES_DB: tta

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
    - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: zhukovgreen@icloud.com
      PGADMIN_DEFAULT_PASSWORD: admin
