version: '3.3'
services:
  api:
    env_file: .env
    build:
      context: .
      cache_from:
      - &img_tag time-tracking-app
    image: *img_tag
    depends_on:
    - redis
    - postgres

  redis:
    image: redis
    ports:
    - 6379:6379

  postgres:
    image: "postgres:11.2"
    environment:
      POSTGRES_USER: tta
      POSTGRES_PASSWORD: tta
      POSTGRES_DB: tta
