"""init

Revision ID: 3505efd09bb2
Revises: 25ca7afc708a
Create Date: 2019-04-25 07:04:33.110960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3505efd09bb2"
down_revision = "25ca7afc708a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "cal_service",
            postgresql.BYTEA(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cal_service")
    # ### end Alembic commands ###
