"""init

Revision ID: 3afc6477b519
Revises: cbb131f7b5ed
Create Date: 2019-04-15 18:31:24.613564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3afc6477b519"
down_revision = "cbb131f7b5ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "currency")
    # ### end Alembic commands ###
