"""init

Revision ID: 40f7dcdf931b
Revises: dc13cc17fd79
Create Date: 2019-04-24 15:26:25.091426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "40f7dcdf931b"
down_revision = "dc13cc17fd79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "cal_id", sa.String(), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "secrets", sa.JSON(), nullable=True
        ),
    )
    op.drop_column("users", "user_calendar_id")
    op.drop_column("users", "auth")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "auth",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "user_calendar_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "secrets")
    op.drop_column("users", "cal_id")
    # ### end Alembic commands ###
