"""init

Revision ID: 55d9bb11f1dd
Revises: f444d45d6d59
Create Date: 2019-04-23 07:19:50.788779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "55d9bb11f1dd"
down_revision = "f444d45d6d59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column(
            "user_id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=True,
        ),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"]
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_column("users", "tags")
    op.drop_column("users", "rate")
    op.drop_column("users", "currency")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###
