"""init

Revision ID: 59cc4ebaf4ea
Revises: 3505efd09bb2
Create Date: 2019-04-25 11:36:15.454198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "59cc4ebaf4ea"
down_revision = "3505efd09bb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_settings",
        sa.Column(
            "user_id", sa.Integer(), nullable=False
        ),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=True,
        ),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"]
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column(
            "user_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="user_settings_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", name="user_settings_pkey"
        ),
        sa.UniqueConstraint(
            "user_id",
            name="user_settings_user_id_key",
        ),
    )
    op.drop_table("report_settings")
    # ### end Alembic commands ###
