"""init

Revision ID: c22ee0047eed
Revises: 80726396cd81
Create Date: 2019-04-25 07:03:08.781686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c22ee0047eed"
down_revision = "80726396cd81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
