"""init

Revision ID: cbb131f7b5ed
Revises: 15e092652285
Create Date: 2019-04-15 18:29:31.510903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbb131f7b5ed"
down_revision = "15e092652285"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("rate", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rate")
    # ### end Alembic commands ###
