"""init

Revision ID: dc13cc17fd79
Revises: f603f5f26ddc
Create Date: 2019-04-24 14:58:42.987705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc13cc17fd79"
down_revision = "f603f5f26ddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_calendar_id",
            sa.String(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_calendar_id")
    # ### end Alembic commands ###
