"""init

Revision ID: f444d45d6d59
Revises: 43ac3b7754ba
Create Date: 2019-04-22 19:29:05.786986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f444d45d6d59"
down_revision = "43ac3b7754ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
