"""init

Revision ID: f603f5f26ddc
Revises: 55d9bb11f1dd
Create Date: 2019-04-24 14:48:35.502851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f603f5f26ddc"
down_revision = "55d9bb11f1dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "user_settings", ["user_id"]
    )
    op.add_column(
        "users",
        sa.Column("auth", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth")
    op.drop_constraint(
        None, "user_settings", type_="unique"
    )
    # ### end Alembic commands ###
